# Generated by Django 5.2.7 on 2025-10-21 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoriaproducto_especificacionproducto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenciasusuario',
            name='preferencia',
        ),
        migrations.RemoveField(
            model_name='preferenciasusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tiendatiposervicio',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='tiendatiposervicio',
            name='tipo_servicio',
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoriaproducto')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TiendaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaproducto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tienda')),
            ],
        ),
        migrations.DeleteModel(
            name='Preferencias',
        ),
        migrations.DeleteModel(
            name='PreferenciasUsuario',
        ),
        migrations.DeleteModel(
            name='TiendaTipoServicio',
        ),
    ]
