# Generated by Django 5.2.7 on 2025-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_preferenciasusuario_preferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
