# Generated by Django 5.2.7 on 2025-10-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chatsession_chatturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendaproducto',
            name='nota_tienda',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tiendaproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiendaproducto',
            name='url_externa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tiendaproducto',
            unique_together={('tienda', 'producto')},
        ),
    ]
