# Generated by Django 5.2.7 on 2025-11-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_is_active_profile_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='atendido',
            new_name='notificacion_leida',
        ),
        migrations.AddField(
            model_name='reporte',
            name='accion_admin',
            field=models.TextField(blank=True, help_text='Notas/instrucciones del administrador'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='admin_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_moderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('revision', 'En revisión'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_accion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='producto_deshabilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.CharField(choices=[('info_incorrecta', 'Información incorrecta'), ('spam', 'Spam o contenido engañoso'), ('duplicado', 'Producto duplicado'), ('otro', 'Otro motivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte_producto', 'Reporte de Producto'), ('producto_eliminado', 'Producto Eliminado'), ('info_incorrecta', 'Información Incorrecta'), ('otro', 'Otro')], help_text='Tipo de notificación', max_length=50)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tienda')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
