# Generated by Django 5.2.7 on 2025-11-05 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_storereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tienda')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
            ],
            options={
                'unique_together': {('tienda', 'tipo_servicio')},
            },
        ),
    ]
