# Generated by Django 5.2.7 on 2025-11-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tienda_url_tienda_alter_reporte_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias_extra',
            field=models.ManyToManyField(blank=True, help_text='Categorias secundarias para este producto sin duplicarlo.', related_name='productos_extra', to='app.categoriaproducto', verbose_name='Categorias adicionales'),
        ),
    ]
