# Generated by Django 5.2.7 on 2025-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productreference'),
    ]

    def copy_references(apps, schema_editor):
        ProductReference = apps.get_model('app', 'ProductReference')
        TiendaProducto = apps.get_model('app', 'TiendaProducto')
        Tienda = apps.get_model('app', 'Tienda')

        listings = TiendaProducto.objects.select_related('tienda')
        bulk = []
        for listing in listings:
            store_name = None
            if listing.tienda_id:
                store_name = listing.tienda.nombre_tienda
            if not store_name:
                store = Tienda.objects.filter(pk=listing.tienda_id).first()
                store_name = store.nombre_tienda if store else "Referencia"
            bulk.append(
                ProductReference(
                    producto_id=listing.producto_id,
                    nombre_fuente=store_name,
                    url_fuente=listing.url_externa or "",
                    precio=listing.precio,
                    stock=listing.stock,
                    nota=listing.nota_tienda or "",
                )
            )
        if bulk:
            ProductReference.objects.bulk_create(bulk, ignore_conflicts=True)

    operations = [
        migrations.RunPython(copy_references, migrations.RunPython.noop),
    ]
