# Generated by Django 5.2.7 on 2025-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_storereview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_budget_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_budget_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
