# Generated by Django 5.2.1 on 2025-10-17 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='especificacion_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especificacion', models.CharField(max_length=100)),
                ('valor_especificacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='marca_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_preferencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='preferencias_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.preferencias')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.TextField()),
                ('modelo_producto', models.CharField(max_length=100)),
                ('imagen_producto', models.ImageField(upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria_producto')),
                ('marca_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca_producto')),
            ],
        ),
        migrations.CreateModel(
            name='productos_favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('email_tienda', models.EmailField(max_length=254, unique=True)),
                ('direccion_tienda', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tienda_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='tienda_tipo_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='especificacion_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
        migrations.AddField(
            model_name='tienda_tipo_servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_servicio'),
        ),
        migrations.AddField(
            model_name='productos_favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='preferencias_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
