# Generated by Django 5.2.1 on 2025-10-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoriaproducto_especificacionproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='banner_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
