# Generated by Django 5.2.7 on 2025-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tiendaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='url_tienda',
            field=models.URLField(blank=True, help_text='URL del sitio web de la tienda', null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.CharField(choices=[('info_incorrecta', 'Información incorrecta'), ('spam', 'Spam o contenido engañoso'), ('duplicado', 'Producto duplicado'), ('otro', 'Otro motivo'), ('servicio_deficiente', 'Servicio deficiente'), ('estafa', 'Posible estafa'), ('incumplimiento', 'Incumplimiento de entrega')], max_length=50),
        ),
    ]
