# Generated by Django 5.2.7 on 2025-11-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_categoriaproducto_categorias_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=120)),
                ('url_fuente', models.URLField(blank=True, max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='app.producto')),
            ],
            options={
                'verbose_name': 'Referencia de producto',
                'verbose_name_plural': 'Referencias de producto',
                'ordering': ['nombre_fuente', 'precio'],
            },
        ),
    ]
