# Generated by Django 5.2.7 on 2025-11-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_copy_tienda_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='tienda',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.CharField(choices=[('info_incorrecta', 'Informaci?n incorrecta'), ('spam', 'Spam o contenido enga?oso'), ('duplicado', 'Producto duplicado'), ('otro', 'Otro motivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='target_type',
            field=models.CharField(choices=[('producto', 'Producto')], default='producto', max_length=20),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='StoreReview',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
        migrations.DeleteModel(
            name='TiendaCategoria',
        ),
        migrations.DeleteModel(
            name='TiendaProducto',
        ),
        migrations.DeleteModel(
            name='TiendaServicio',
        ),
        migrations.DeleteModel(
            name='TipoServicio',
        ),
    ]
