# Generated by Django 5.2.7 on 2025-11-13 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_preference_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('brand', 'Marca'), ('category', 'Categoria'), ('type', 'Tipo de producto'), ('price_band', 'Rango de precio')], max_length=20)),
                ('key', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadistica de vista',
                'verbose_name_plural': 'Estadisticas de vistas',
                'unique_together': {('usuario', 'metric', 'key')},
            },
        ),
    ]
