# Generated by Django 5.2.7 on 2025-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userviewstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_budget_manual',
            field=models.BooleanField(default=False),
        ),
    ]
