# Generated by Django 5.2.7 on 2025-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_referencevisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatturn',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatturn',
            name='productos_sugeridos',
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Nuevo'), ('pendiente', 'En revision'), ('resuelto', 'Resuelto')], default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.CharField(choices=[('info_incorrecta', 'Informacion incorrecta'), ('spam', 'Spam o contenido enganoso'), ('duplicado', 'Producto duplicado'), ('otro', 'Otro motivo')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='ChatTurn',
        ),
    ]
